// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCabm4n5jKSLvWT6tkUWmeNktG-FVnf6ks',
    appId: '1:398100703534:web:ac5c17e55896b1729c32bf',
    messagingSenderId: '398100703534',
    projectId: 'thesisapp-2c27a',
    authDomain: 'thesisapp-2c27a.firebaseapp.com',
    storageBucket: 'thesisapp-2c27a.firebasestorage.app',
    measurementId: 'G-8MQH5FYQNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCgY5ZwD3tiDB3fyWww4lsVpl5iqFO-yI',
    appId: '1:398100703534:android:7392f98326e6d45d9c32bf',
    messagingSenderId: '398100703534',
    projectId: 'thesisapp-2c27a',
    storageBucket: 'thesisapp-2c27a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTjBgQSlKtMeC_Bw-fyRJuNNLl-qjAF5c',
    appId: '1:398100703534:ios:7def6035c17894949c32bf',
    messagingSenderId: '398100703534',
    projectId: 'thesisapp-2c27a',
    storageBucket: 'thesisapp-2c27a.firebasestorage.app',
    iosBundleId: 'com.example.urinalysisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTjBgQSlKtMeC_Bw-fyRJuNNLl-qjAF5c',
    appId: '1:398100703534:ios:7def6035c17894949c32bf',
    messagingSenderId: '398100703534',
    projectId: 'thesisapp-2c27a',
    storageBucket: 'thesisapp-2c27a.firebasestorage.app',
    iosBundleId: 'com.example.urinalysisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCabm4n5jKSLvWT6tkUWmeNktG-FVnf6ks',
    appId: '1:398100703534:web:8ab34fa818d4f3299c32bf',
    messagingSenderId: '398100703534',
    projectId: 'thesisapp-2c27a',
    authDomain: 'thesisapp-2c27a.firebaseapp.com',
    storageBucket: 'thesisapp-2c27a.firebasestorage.app',
    measurementId: 'G-70KQG04PKR',
  );
}
